#include "main.h"

struct skill_i
{
	const char*			name[2];
} skill_data[] = {
	{{"Acrobatics", "Акробатика"}},
	{{"Alchemy", "Алхимия"}},
	{{"Alertness", "Бдительность"}},
	{{"Ambushing", "Засада"}},
	{{"Animal Husbandry", "Уход за животными"}},
	{{"Animal Training", "Тренировка животных"}},
	{{"Apostasy", "Отступник"}},
	{{"Arcane Dabbling", "Мистический фокусник"}},
	{{"Painting", "Рисование"}},
	{{"Bargaining", "Торговля"}},
	{{"Battle Magic", "Боевая магия"}},
	{{"Beast Friendship", "Дружба с бестиями"}},
	{{"Berserkergang", "Берсеркерство"}},
	{{"Black lore of Zahar", "Черные знания Захары"}},
	{{"Blind fighting", "Сражение ослепленным"}},
	{{"Bribery", "Подкуп"}},
	{{"Caving", "Пещероведение"}},
	{{"Cat burglary", "Кошачья ловкость"}},
	{{"Climbing", "Лазание"}},
	{{"Collegiate wizardry", "Коллегиальный волшебник"}},
	{{"Combat reflexes", "Боевые рефлексы"}},
	{{"Combat trickery", "Уловки боя"}},
	{{"Command", "Командование"}},
	{{"Contemplation", "Созерцание"}},
	{{"Contortionism", "Гибкость"}},
	{{"Smithing", "Кузнечное дело"}},
	{{"Diplomacy", "Дипломатия"}},
	{{"Disguise", "Перевоплощение"}},
	{{"Divine blessing", "Святое благословение"}},
	{{"Divine health", "Святое здоровье"}},
	{{"Dungeon bashing", "Выбивание дверей"}},
	{{"Dwarven brewing", "Гномье пивоварение"}},
	{{"Eavesdropping", "Наблюдательность"}},
	{{"Elementalism", "Элементализм"}},
	{{"Endurance", "Выносливость"}},
	{{"Engineering", "Инженерное дело"}},
	{{"Familiar", "Спутник"}},
	{{"Dual weapon fighting", "Сражение двумя оружиями"}},
	{{"Marksmanship", "Меткость"}},
	{{"Polearm fighting", "Сражение древковым оружием"}},
	{{"Single weapon fighting", "Сражение одним оружием"}},
	{{"Two-handed weapon fighting", "Сражение двуручным оружием"}},
	{{"Weapon and shield fighting", "Сражение оружием и щитом"}},
	{{"Gambling", "Азартные игры"}},
	{{"Goblin-slaying", "Убийца гоблинов"}},
	{{"Healing", "Лечение"}},
	{{"Illusion resistance", "Сопротивление иллюзии"}},
	{{"Intimidation", "Запугивание"}},
	{{"History", "История"}},
	{{"Mining", "Шахтерство"}},
	{{"Land surveying"}},
	{{"Laying on hands", "Возложение рук"}},
	{{"Leadership", "Лидерство"}},
	{{"Lip reading", "Чтение по губам"}},
	{{"Lockpicking", "Взломщик"}},
	{{"Loremastery", "Министрель"}},
	{{"Magical music", "Волшебный музыкант"}},
	{{"Mapping", "Картография"}},
	{{"Martial training", "Боевое искусство"}},
	{{"Military strategy", "Военная стратегия"}},
	{{"Mimicry", "Мимикрия"}},
	{{"Mountaineering", "Скалолазание"}},
	{{"Mystic aura", "Мистическая аура"}},
	{{"Naturalism", "Натурализм"}},
	{{"Navigation", "Навигация"}},
	{{"Passing without trace", "Движение без следов"}},
	{{"Dancing", "Танцы"}},
	{{"Precise shooting", "Точные выстрелы"}},
	{{"Prestidigitation", "Фокусы"}},
	{{"Scribing", "Писарь"}},
	{{"Prophecy", "Предназначение"}},
	{{"Quiet magic", "Тихие заклинания"}},
	{{"Riding", "Езда верхом"}},
	{{"Righteous turning", "Праведное изгнание"}},
	{{"Running", "Марафонец"}},
	{{"Seafaring", "Мореплавание"}},
	{{"Seduction", "Соблазнение"}},
	{{"Sensing evil", "Чувство зла"}},
	{{"Sensing power", "Чувство магии"}},
	{{"Signaling", "Передача сигналов"}},
	{{"Skirmishing", "Налетчик"}},
	{{"Skulking", "Скрытность"}},
	{{"Sniping", "Снайпер"}},
	{{"Survival", "Выживание"}},
	{{"Swashbuckling", "Сорвиголова"}},
	{{"Theology", "Теология"}},
	{{"Trap finding", "Поиск ловушек"}},
	{{"Tracking", "Выслеживание"}},
	{{"Transmogrification"}},
	{{"Trapping", "Трапперство"}},
	{{"Weapon finesse", "Фехтование"}},
	{{"Bows focus", "Специалист по лукам"}},
	{{"Swords focus", "Специалист по мечам"}},
	{{"Axes focus", "Специалист по топорам"}}
};
assert_enum(skill, LastSkill);
getstr_enum(skill);